--- 
leen_laptop: 
  excludes: 
  - c/Users/leen/AppData/Local/Temp
  includes: 
  - root/c/Users
  - root/d/Leen
linux: fs_linux.yaml
android: 
  excludes: 
  - /acct
  - /proc
  - /dev
  - /sys
  - /tmp
  - /mnt
  - /storage
  - /Removable
  includes: 
  - /
android2: 
  excludes: 
  - /acct
  - /proc
  - /dev
  - /sys
  - /tmp
  - /mnt
  - /Removable
  includes: 
  - /
  - /mnt/sdcard
