--- 
:excludes: 
- /proc
- /dev
- /sys
- /tmp
- /media
- /mnt
- /home/*/.gvfs
- /home/*/tmp
- /var/lib/mysql
- /swap.swp
- /usr/doc
- /usr/local/mysql
- /data
- /andere
- /Windows
- /tftpboot
- /storage/Media
- /storage/pictures
- /storage/andere
- /var/media
- /pictures
- /virtual
:includes: 
- /
