--- 
transformer: 
  rsync_path: /system/xbin/rsync
  contact: jo.vandeginste@gmail.com
  cycle: TripleDaily
  connect: transformer
  prune_after: 5184000
  mode: linux
  fileset: android
leen_laptop: 
  contact: jo.vandeginste@gmail.com
  cycle: Laptop
  connect: 
    leen-laptop: {}

    leen-laptop-wifi: 
      cycle: TripleDaily
  mode: windows
  fileset: leen_laptop
dwarfy: 
  contact: jo.vandeginste@gmail.com
  cycle: Daily
  connect: old.dwarfy.be
  mode: linux
  fileset: linux
spid3r_linux: spid3r_linux.yaml 
openelec: 
  rsync_path: /storage/bin/rsync
  contact: jo.vandeginste@gmail.com
  cycle: TripleDaily
  connect: openelec
  prune_after: 5184000
  mode: linux
  fileset: linux
mediacenter: 
  contact: jo.vandeginste@gmail.com
  cycle: Monthly
  connect: mediacenter
  mode: linux
  fileset: linux
new_dwarfy: 
  contact: jo.vandeginste@gmail.com
  cycle: Daily
  connect: new.dwarfy.be
  mode: linux
  fileset: linux
pi1: 
  contact: jo.vandeginste@gmail.com
  cycle: Daily
  connect: pi1
  mode: linux
  fileset: linux
